name: Test Workflow

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
      - name: Build
        run: npm run build

      - name: Echo the name
      - run:  |
      | export NAME=Nils
      | echo the $NAME
  
  deploy:
    runs-on: ubuntu-latest

    # wait for first job ok, of not it's simultaneous
    needs: build-test
    
    steps:
      # fetch le code du repository
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.JOKE_APP_TOKEN}}
          heroku_app_name: "joke" #Must be unique in Heroku
          heroku_email: "compte.mxs@hotmail.fr"